### ISSUE TITLE
PublicHolidaysAdaptiveCardExtension: is not initialized

### ISSUE THREAD

**Issue by blueitpro** [pnp/sp-dev-fx-aces#122]
## Authors

@nanddeepn 
@ravi16a87
@SmitaNachan

## Expected or Desired Behavior
Display Public Holidays

## Observed Behavior

at t._getRenderArguments (https://res-1.cdn.office.net/files/sp-client/sp-adaptive-card-extension-base_en-us_2856abecc053ce38a08e.js:1:29486)
at t.update (https://res-1.cdn.office.net/files/sp-client/sp-adaptive-card-extension-base_en-us_2856abecc053ce38a08e.js:1:29187)
at t._navigatorCallback [as _handleStackChangedCallback] (https://res-1.cdn.office.net/files/sp-client/sp-adaptive-card-extension-base_en-us_2856abecc053ce38a08e.js:1:23744)
at e.replace (https://res-1.cdn.office.net/files/sp-client/sp-adaptive-card-extension-base_en-us_2856abecc053ce38a08e.js:1:20109)

at t.<anonymous> (https://tenant.sharepoint.com/sites/Apps/ClientSideAssets/d19e1ab6-ebe7-4abb-92a5-e6ba9cfc370d/public-holidays-adaptive-card-extension_9a977e6d0b5d976a07b5.js:2:79637)
at https://tenant.sharepoint.com/sites/Apps/ClientSideAssets/d19e1ab6-ebe7-4abb-92a5-e6ba9cfc370d/public-holidays-adaptive-card-extension_9a977e6d0b5d976a07b5.js:2:78234
at Object.next (https://tenant.sharepoint.com/sites/Apps/ClientSideAssets/d19e1ab6-ebe7-4abb-92a5-e6ba9cfc370d/public-holidays-adaptive-card-extension_9a977e6d0b5d976a07b5.js:2:78339)
at https://tenant.sharepoint.com/sites/Apps/ClientSideAssets/d19e1ab6-ebe7-4abb-92a5-e6ba9cfc370d/public-holidays-adaptive-card-extension_9a977e6d0b5d976a07b5.js:2:77275
at new Promise (<anonymous>)
at st (https://tenant.sharepoint.com/sites/Apps/ClientSideAssets/d19e1ab6-ebe7-4abb-92a5-e6ba9cfc370d/public-holidays-adaptive-card-extension_9a977e6d0b5d976a07b5.js:2:77023)

# Environment Details (*Development & Target environment*)

- **OS**: [Windows 11]
- **Target Environment**: [SharePoint Online]
- **Browser(s)**: [Edge]
- **Tooling**: [VS Code | SPFx v1.10.0 ]

**Comment by nanddeepn** [comment]
Hi @blueitpro 
Thank you for reporting. I will have a look and fix.

**Comment by nanddeepn** [comment]
Hi @blueitpro 
PR is raised at https://github.com/pnp/sp-dev-fx-aces/pull/123. It should be merged soon.

**Comment by blueitpro** [comment]
@nanddeepn Thank you for the fix, when can we expect this to be available?

**Comment by nanddeepn** [comment]
Thank you @blueitpro 
The Repo maintainer @dcashpeterson will review and merge the PR soon.

**Comment by nanddeepn** [comment]
Thank you @dcashpeterson ❤️

**Comment by hsantan** [comment]
sppkg published doesn't have the fixed version. Can you publish the new version?

**Comment by nanddeepn** [comment]
Hi @hsantan 
This issue is closed. Can you please create a new one [here](https://github.com/pnp/sp-dev-fx-aces/issues)?
Thank you.
