### ISSUE TITLE
BASICCARD-MULTIPLE-FORMS-APPS: NodeJS Version

### ISSUE THREAD

**Issue by vdowney** [pnp/sp-dev-fx-aces#154]
## Sample
BASICCARD-MULTIPLE-FORMS-APPS

## Authors

Marcus Castro

## Expected or Desired Behavior

Running "gulp build --ship"

Successful run

## Observed Behavior

Error: Your dev environment is running NodeJS version v18.18.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0 || >=16.13.0 <17.0.0
    at SPWebBuildRig.initialize (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\sp-build-web\lib\SPBuildRig.js:27:19)
    at Object.initialize (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\sp-build-web\lib\index.js:36:17)
    at Object.<anonymous> (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\gulpfile.js:16:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at requireOrImport (C:\Users\****\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)

## Steps to Reproduce

1. Go to 'PowerShell window'
2. Navigate to proper folder
3. Type "gulp build --ship"

# Environment Details (*Development & Target environment*)

- **OS**: Windows 11
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v18.18.0
- **Browser(s)**: Edge
- **Tooling**: VS Code
- **Additional details**: Running command in Windows PowerShell

**Comment by a1mery** [comment]
The BasicCard-Multiple-Forms-Apps sample is using SPFx version 1.16.1. This version is not compatible with Node.js v18.
Check this table for more information: [SPFx development environment compatibility](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility)
