### ISSUE TITLE
BasicCard-Multiple-Forms-Apps: Eslinit issue on gulp serve

### ISSUE THREAD

**Issue by vdowney** [pnp/sp-dev-fx-aces#156]
## Sample
BasicCard-Multiple-Forms-Apps

## Authors

Marcus Castro

## Expected or Desired Behavior

Process gulp serve

## Observed Behavior

Error - [lint] Unexpected STDERR output from ESLint:
Oops! Something went wrong! :(
ESLint: 8.7.0
TypeError: Cannot read properties of undefined (reading 'getFirstToken')
Occurred while linting C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\src\adaptiveCardExtensions\aceForms\AceFormsAdaptiveCardExtension.ts:30
Rule: "@typescript-eslint/no-extra-semi"
    at ClassBody (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\eslint\lib\rules\no-extra-semi.js:130:52)
    at ruleErrorHandler (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\linter.js:1079:28)
    at C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:795:23)
    at C:\Users\****\Documents\Projects\Samples\sp-dev-fx-aces\samples\BasicCard-Multiple-Forms-Apps\node_modules\@microsoft\rush-stack-compiler-4.5\node_modules\eslint\lib\linter\linter.js:1110:32

## Steps to Reproduce

1. Go to 'Windows PowerShell'
2. Go to BasicCard-Multiple-Forms-Apps folder
3. Type gulp serve

# Environment Details (*Development & Target environment*)

- **OS**: Windows 11
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v16.20.2
- **Browser(s)**: Edge
- **Tooling**: VS Code
- **Additional details**: Windows PowerShell

**Comment by a1mery** [comment]
I cannot reproduce the issue on my side :(
Have you tried removing all node modules and running again `npm install` after installing the correct version of Node.js ?
Otherwise maybe this previous issue could help you: [https://github.com/SharePoint/sp-dev-docs/issues/9006](https://github.com/SharePoint/sp-dev-docs/issues/9006)

**Comment by dcashpeterson** [comment]
@vdowney I was not able to reproduce the error either. In looking at the issue @a1mery linked to I am running V 1.17 of the generator so that could explain it. Let us know if this fixes the issue.

**Comment by anoopt** [comment]
@a1mery - Can you please let us know the node version you are using?

When I try to build the sample with the below versions, I am seeing the same error mentioned.

Project spfx-ace-forms version: 0.0.1
Build tools version: 3.17.19
Node version: v16.18.1

**Comment by anoopt** [comment]
@vdowney as mentioned in the issue shared by @a1mery, please run `npm dedupe` that should resolve the issue.

I no longer see the issue after running `npm dedupe`.

**Comment by a1mery** [comment]
> @a1mery - Can you please let us know the node version you are using?
> 
> When I try to build the sample with the below versions, I am seeing the same error mentioned.
> 
> Project spfx-ace-forms version: 0.0.1 Build tools version: 3.17.19 Node version: v16.18.1

I'm using node v16.13.0

**Comment by vdowney** [comment]
Thank you, running "npm dedupe" resolved the issue.
